### ISSUE TITLE
License for animations

### ISSUE THREAD

**Issue by bruteforks** [Animation-Uprising/MotionSymphony_ExampleProject#12]
Hello. Thanks for the project! I'm wondering, did you create these animations, or acquire them from somewhere? I would like to know their provenance before using them in my project. Thanks!

> Commercial Use: You are free to use any assets within this project for commercial use, royalty free.

**Comment by Avindr** [comment]
I created them myself. You can use them as you wish commercially or otherwise.

**Comment by bruteforks** [comment]
thanks! they look great, and really appreciate you offering them to the community. you're a life saver!
