### ISSUE TITLE
Example project fails to compile if not using source

### ISSUE THREAD

**Issue by Avindr** [Animation-Uprising/MotionSymphony_ExampleProject#2]
If the plugin is installed to the engine (instead of using source) the project fails to compile.
A solution for this has been found and the plugin will be updated as soon as possible. 

In the meantime, consider using the plugin source. Request source access via the support email and provide your invoice number.

**Comment by Avindr** [comment]
A fix for this has been submitted to the Epic Marketplace for approval and should be available soon.

**Comment by ziocleto** [comment]
Hi, is this the error log this issue is referring to? 

`LogCompile: Error: An explicit Category specifier is required for Blueprint accessible functions in an Engine module.`

If so, what's the support email I can't see to find it anywhere?

Cheers,
Dado.

**Comment by Avindr** [comment]
Yes that's correct. Support email is claassen.ken@gmail.com. Though you can also join the Discord (see documentation link) and request source access there.

**Comment by Avindr** [comment]
Unfortunately I missed one explicit category in the last update. This has been rectified and re-submitted. Shouldn't be any problems going forward from the next update (whenever Epic approve that file update).
