### ISSUE TITLE
Peculiar startup error on blueprint, using plugin from source

### ISSUE THREAD

**Issue by ziocleto** [Animation-Uprising/MotionSymphony_ExampleProject#3]
Hi!

I'm not sure if I've got something in my setup since I'm running the example linking the plugin from source for the time being, but it looks like I'm greeted with a few errors at startup:

![image](https://user-images.githubusercontent.com/9387545/119754557-9b047880-be98-11eb-80af-87f7c50f217e.png)
![image](https://user-images.githubusercontent.com/9387545/119754781-d43ce880-be98-11eb-855e-b37a9d1782e1.png)

Opening the offending blueprint I have this:

![image](https://user-images.githubusercontent.com/9387545/119754836-e9b21280-be98-11eb-8ac6-d41f2f7c5a11.png)

![image](https://user-images.githubusercontent.com/9387545/119754851-f0408a00-be98-11eb-969c-a7c80a5c376f.png)

There's an easy fix as I can just relink that missing file, but somehow even if I save the BP and the whole project, at the next restart the error re-appears. very strange!

Cheers,
Dado.

**Comment by Avindr** [comment]
Hi, Thanks I'm aware of this one. I find that sometims of the time I just have to click compile and it's all good again. Either way I think it is an issue with load order that I'll try to fix soon.

**Comment by Avindr** [comment]
This has been fixed in a recent update, both on github and the marketplace.
