### ISSUE TITLE
There may be a bug in FAnimNode_MotionMatching::EvaluateSinglePose function

### ISSUE THREAD

**Issue by hui211314dd** [Animation-Uprising/MotionSymphony_ExampleProject#5]
version: Motion Symphony v1.05

Cpp:     AnimNode_MotionMatching.cpp

if(MotionSequence.bLoop)
			{
				AnimTime = FMotionMatchingUtils::WrapAnimationTime(AnimTime, AnimSequence->GetPlayLength());
			}

#if ENGINE_MAJOR_VERSION > 4 || ENGINE_MINOR_VERSION > 25
			FAnimationPoseData AnimationPoseData(Output);
			AnimSequence->GetAnimationPose(AnimationPoseData, FAnimExtractContext(PrimaryChannel.AnimTime, true));
#else
			AnimSequence->GetAnimationPose(Output.Pose, Output.Curve, FAnimExtractContext(PrimaryChannel.AnimTime, true));
#endif

Should "PrimaryChannel.AnimTime" be replaced by local param "AnimTime" ？
thanks.

**Comment by Avindr** [comment]
Hi,

I don't understand what you are trying to say here. Could you please explain more clearly what the bug is and what engine version you are using.? 

Also please title bug reports appropriately. "bug" is not a helpful title and I can't action this without further information.

**Comment by hui211314dd** [comment]
> Hi,
> 
> I don't understand what you are trying to say here. Could you please explain more clearly what the bug is and what engine version you are using.?
> 
> Also please title bug reports appropriately. "bug" is not a helpful title and I can't action this without further information.

I have modified the problem description,sorry about that.

**Comment by Avindr** [comment]
Hi,

Yes you are correct. I have fixed this and it will be included in the next update. 

Cheers
